language: go
sudo: false

go:
  - 1.8.x
  - tip

before_install:
  - go get -t -v ./...

script:
  - chmod 777 *
  - ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) -t cbd74805-3add-4079-8f25-1d39e3fa2528
