sudo: false
language: go
go:
  - 1.7.x
  - 1.8.x
  - master

install:
  - go get -t -v ./...
  - go get -u github.com/golang/lint/golint

script:
  - go test -v -race ./...
  - golint ./...

matrix:
  allow_failures:
    - go: master
  fast_finish: true
